version: '3.8'

services:
  vibe-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: vibe-db
    volumes:
      - ./pgdata:/var/lib/postgresql/vibe
    ports:
      - '5435:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - vibe-db